title: Truly Crisp
url: "https://trulycrisp.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: dark

plugins:
- jekyll-include-cache
- jekyll-feed
- jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      toc: true
      sidebar:
        nav: main
  - scope:
      path: drivefirmware
    values:
      sidebar:
        nav: drivefirmware
